### ISSUE TITLE
MMA in your code.

### ISSUE THREAD

**Issue by edgar-explorer** [axelBarroso/Key.Net#1]
Hi, thank you for your good work. I am confused with MMA in your code when testing  Please help me, thank you. When I use different pixel-threshold and get Matching Score, Matching Score (possible matches) and Num matches, but MMA result is the same. Is something wrong with your code? MMA is overall image pairs defined, for a fixed threshold t in pixels, by:
![image](https://user-images.githubusercontent.com/24315713/67837851-f6d71600-fb2a-11e9-9e22-99ff248ead4b.png)
In addition, I am also confused with the 173 line in hsequeces_bench.py:
 for th_i in range(1, 11)
Thank you.

**Comment by axelBarroso** [comment]
Hi, thank you for your message. It was a nomenclature problem, I renamed correctly the metrics now.

Moreover, line 173 is used to compute the MMA over different thresholds. 

Best,
Axel
