### ISSUE TITLE
extract color image keypoints

### ISSUE THREAD

**Issue by AmmarKamoona** [axelBarroso/Key.Net#10]
Hi there, 
Does the code work to color images. I have seen in your code that you have converted the color image to a binary one. My question, why don't you feed color images directly to the network.

**Comment by axelBarroso** [comment]
Hello,

That is a good question. You could train many detectors with color images, even in the Key.Net framework. The problem though for Key.Net is that it uses handcrafted operators (sobel filters) to compute the first set of features. Therefore, if you want to use color images in Key.Net, you may either remove the handcrafted block or combine the color image with handcrafted features before the learned block (among many other possibilities).
