### ISSUE TITLE
i change the number of desired features to extract, but the result is not change

### ISSUE THREAD

**Issue by Berumotto1** [axelBarroso/Key.Net#13]
hello
when i change the number of desired features to extract in tensorflow, the result is not change.
But the result of the pytorch version changes with the number of desired features to extract.

**Comment by axelBarroso** [comment]
Hello,

Both versions of Key.Net extract local features such that the final number of keypoint candidates is given by _min(detected_features, desired_features)_. If for an image the number of detected features is lower than the number of desired features, it will always return the same number (# detected_features).

Also note that even though TF and PyTorch implementations of Key.Net are very similar, they are not exactly the same, and you could experience different results when comparing both of them.

Hope it helps.
