### ISSUE TITLE
Key.Net-TI

### ISSUE THREAD

**Issue by Berumotto1** [axelBarroso/Key.Net#14]
hello, excause me.
I found the paper mentioning that Key.Net-TI is robust to illumination, how do I get it?
thank you

**Comment by axelBarroso** [comment]
Hello, 

Key.Net-TI refers to the single-scale extraction (TI = Translation Invariant). That means that we do not run the Gaussian pyramid to extract multi-scale features but do only extraction on the original image resolution size. TI is a better choice if the pairs of images you want to match have only illumination perturbations. For that, you need to use the argument extract-MS (in extract_multiscale_features.py) and set it to False. 

Hope this helps.
