### ISSUE TITLE
Inference time is abnormal

### ISSUE THREAD

**Issue by xiaochenFang** [axelBarroso/Key.Net#2]
hello
When I use extract_multiscale_features.py  to compute the features from HSequences with default configuration，It will cost about 1000ms per image，how can I get the result as your paper show？
my environment：
ubuntu16.04
python = 3.7
tensorflow_gpu = 1.13.1
cuda = 10.1
cudnn = 7.65
RTX2080 super
thank U！

**Comment by axelBarroso** [comment]
Hello, 

Time in the paper is the inference network time, meaning that we reported the time expended in the sess.run(). Meanwhile, in extract_multiscale_features, there are multiple sess.run(), each for one scale level, in addition, after sess.run() we perform NMS, and we extract top k points and their associated descriptors. This full pipeline makes the total time bigger. 

Best,
Axel
