### ISSUE TITLE
error in keynet.aux.tools

### ISSUE THREAD

**Issue by sushma1910** [axelBarroso/Key.Net#3]
trying to run in google colab
File "keynet/Key.Net-master/extract_multiscale_features.py", line 5, in <module>
    import keyNet.aux.tools as aux
ModuleNotFoundError: No module named 'keyNet.aux'

**Comment by axelBarroso** [comment]
Hello, 

Seems that the path is somehow wrong. Try to check that you are in the correct directory, and therefore, you can import the module keynet.aux. I haven't run it on colab, but this error seems to be more related to paths than with the environment. 

Best,

**Comment by coderdud** [comment]
I have the same issue.
I can't find aux.

Traceback (most recent call last):
  File "extract_multiscale_features.py", line 5, in <module>
    import keyNet.aux.tools as aux
ModuleNotFoundError: No module named 'keyNet.aux'

**Comment by coderdud** [comment]
found the problem:
on win10 aux is a reserved name.
to use it should change the aux folder to something else.

**Comment by axelBarroso** [comment]
Hi, 

Thanks for letting us know! We will change the folder name to avoid any problem with Win10 users! 

Best,

**Comment by tjennings-cra** [comment]
Is there any update on this? It looks like `aux` is still one of the folder names.
