### ISSUE TITLE
New Results of Matching score after moving to official Hardnet Pytorch Implementation.

### ISSUE THREAD

**Issue by usamasadiq706** [axelBarroso/Key.Net#4]
Hi, hello. 
May you please provide me with the new results of  matching score of hpatches data set that you computed after moving from hard net tensor flow to official hard net PyTorch implementation. 
Thanking you in advance.

**Comment by axelBarroso** [comment]
Hello, the new results with official HardNet implementation are the following ones:

```
Key.Net-SI Viewpoint:
## Overlap @0.6: #### MMA: 0.4645

Key.Net-SI Illumination:
## Overlap @0.6: #### MMA: 0.4848

Key.Net-TI Viewpoint:
## Overlap @0.6: #### MMA: 0.4340

Key.Net-TI Illumination:
## Overlap @0.6: #### MMA: 0.4971
```

Note that all matching Key.Net paper results should be updated with official HardNet for a fair comparison.

**Comment by yujieNC** [comment]
Hello, MMA here is just the Matching score in Key.Net paper, is it? @axelBarroso
