### ISSUE TITLE
Could you explain the output from hsequeces_bench.py?

### ISSUE THREAD

**Issue by GabbySuwichaya** [axelBarroso/Key.Net#5]
Thank you for releasing the codes. I enjoy reading your paper. 

I find that the way you report the results in Table 2  (Repeatability results) in the paper is quite interesting. So, I tried executing `hsequeces_bench.py`.  However, I am a little confused by how each of these outputs is related to table 2 in the paper. 

It would be nice if you could correct my understanding and clarify. 

Let's say, for example, I extract Key.Net with (default setting ) on the Hpatch dataset and run hsequeces_bench.py.  Then, I get the following number when using --split "view" (--top-k-points 1000). 

#### Rep. Single: 68.9656  <<   Is this Repeatability (L) ? 
             #### Overlap Multi: 0.0939   <<  Is this Overlap (SL) ? 
             #### Overlap Single: 0.1846 <<  Is this Overlap (L) ? 
             #### MMA: 0.4645
             #### MMA (possible matches): 0.5906
             #### Num matches: 426.9932
             #### Num Mutual Correspondences: 491.8339
             #### Avg. over Threshold MMA: 0.4262
             #### Num Feats: 901.4712

1.  If I just look at the value of repeatability, it seems that .....

-  The multiscale-based calculation results, such as Rep. Multi and Overlap Multi, are using the actual scale and location (SL) in computing... 

-  The signal-based calculation results, such as Rep. Single and Overlap Single, are using only the actual location (L) in computing... 

Is my understanding correct? It would be great if you could confirm, or clarify my misunderstanding. 

I was a little confused because there are also Key.Net-TI and Key.Net-SI ... But it seems that by default, the feature extraction is set in  Key.Net-SI mode.  

2. I used the default setting with --split "view"; however, I get the lower repeatability  as well as the lower Overlapping such as  

#### Rep. Single: 68.9656 << But in the paper Rep  L has the value at about 73.2 ??    
             #### Overlap Multi: 0.0939    << But in the paper Overlap SL has the value at about 0.19 ??   
             #### Overlap Single: 0.1846  << But in the paper Overlap L has the value at about   0.14 ?? 
 
What should I adjust in the feature extraction & `hsequeces_bench.py` setting in order to get similar results?

**Comment by axelBarroso** [comment]
Hello, 

You are correct:

- Multiscale-based calculations use scale and location (SL).
- Single scale-based calculations use only locations (L).

The weights released of Key.Net's model were computed after submitting the paper, and results vary a bit from it. We used closer variations (viewpoint and especially illumination) to real 3D data when generating the new synthetic training set. The newest weights performed better on the real 3D scenarios, and we, therefore, kept them over the previous ones. Although its new performance in viewpoint is slightly lower, results for illumination and 3D reconstruction are higher. I leave you the results for Key.Net-SI and Key.Net-TI for both splits for your reference:

**Key.Net-SI Viewpoint:**
`## Overlap @0.6:
            #### Rep. Multi: 56.7269
            #### Rep. Single: 68.9656
            #### Overlap Multi: 0.0939
            #### Overlap Single: 0.1846
            #### MMA: 0.4645`

**Key.Net-SI Illumination:**
`## Overlap @0.6:
            #### Rep. Multi: 63.8985
            #### Rep. Single: 67.4931
            #### Overlap Multi: 0.0919
            #### Overlap Single: 0.0900
            #### MMA: 0.4848`


**Key.Net-TI Viewpoint:**
`## Overlap @0.6:
            #### Rep. Multi: 33.7054
            #### Rep. Single: 71.3178
            #### Overlap Multi: 0.1136
            #### Overlap Single: 0.2027
            #### MMA: 0.4340`

**Key.Net-TI Illumination:**
`## Overlap @0.6:
            #### Rep. Multi: 75.7830
            #### Rep. Single: 75.7846
            #### Overlap Multi: 0.1117
            #### Overlap Single: 0.1117
            #### MMA: 0.4971`

In addition, you can check how Key.Net performs on real scenarios against other SOTA methods in the CVPR 2020 Image Matching Workshop: https://vision.uvic.ca/image-matching-challenge/leaderboard/

**Comment by GabbySuwichaya** [comment]
Thank you very much !!! It is great to know.

**Comment by GabbySuwichaya** [comment]
By the way, in your script (https://github.com/axelBarroso/Key.Net/blob/master/hsequeces_bench.py#L233).... 
The display of Overlap Multi and Overlap Single is swapped.  So, I guess ..... The result should be the Overlap Multi: 0.1846  #### Overlap Single: 0.0939

**Comment by axelBarroso** [comment]
True, thank you so much for spotting it! Will change it! :)
