### ISSUE TITLE
Could you advice how to use hsequeces_bench.py for features with fixed size image

### ISSUE THREAD

**Issue by GabbySuwichaya** [axelBarroso/Key.Net#6]
Hello! Thanks for the great work. I have tried to properly use the evaluation hsequeces_bench.py. I find this evaluation quite interesting. I actually like to study the performance of each algorithm and see what is their strength.  

Here, I wonder how to set the hsequeces_bench.py for some features (similar to SuperPoint) that extracted features from scaled image size such as [480, 640].  It seems that the ground truth homographic translation is provided based on the ground truth image size.  

So, I am not sure if I can rescale the input image to the fixed size, then will I get the correct results, or should I rescale the keypoint position to the original image size?  Or how did you do it with SuperPoint?   

I know it is actually not your work and it may be a little bit too much to ask for your help.
But, it would be great to gain more understanding.

**Comment by axelBarroso** [comment]
Hi, that's good, thanks for checking the code! 

Yes, if you are using the provided homography matrixes from the HPatches benchmark, you need to use the features with the original size coordinates. 

Although, if you want to evaluate methods that need resizing, you can easily find a workaround to use our evaluation code:

- You can avoid the resizing step before the feature extraction. You should check if methods perform correctly if no resizing was performed. Additionally, you need a GPU that is able to handle such methods when using bigger input size images.
- You can normalize the Homography matrix.
- You can rescale the keypoints coordinates once they have been extracted with the inverse factor that was used to resize the input image. I would suggest starting with this solution, it is easy and should show good results. 

Good luck.

**Comment by GabbySuwichaya** [comment]
Thanks for the answer. I will try it. 

By the way, I also wonder why the radius is set to 30. Is it because of the NMS operation that is based on the window size of 15x15 as described in the paper? However, it seems that this part is not in hsequeces_bench.py. 

Also, how do you pick the radius for other comparison algorithms? Are they all set to 30?

**Comment by axelBarroso** [comment]
Hi, 

The radius of 30 pixels is to normalize the different range of keypoint scales among detectors. It is not related to our 15x15 NMS. It is now a standard value that was presented in "Large scale evaluation of local image feature detectors on homography datasets" (https://arxiv.org/abs/1807.07939).

**Comment by GabbySuwichaya** [comment]
I see..... Thanks so much for sharing.  :)
