### ISSUE TITLE
The Gaussian Kernel

### ISSUE THREAD

**Issue by zcx-language** [axelBarroso/Key.Net#7]
The gaussian kernel formula in the file 'keynet_architecture.py' may be wrong, or you design it on purpose. 

![image](https://user-images.githubusercontent.com/38426607/100617264-389d4600-3355-11eb-90ff-433b957af024.png)

**Comment by axelBarroso** [comment]
Hi, thanks for pointing that out! 

You are right, we mixed the 1-D and 2-D definition of the Gaussian kernel. We will correct it and commit the corrected kernel together with the new Key.Net's weights.
